version: '3.8'
services:
  vue-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://host.docker.internal:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # flask-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.flask
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - FLASK_ENV=development
  #   # Grant access to camera devices
  #   devices:
  #     - /dev/video0:/dev/video0
  #   # Additional privileges for camera access
  #   privileged: true
  #   # Alternative to privileged (more secure)
  #   # cap_add:
  #   #   - SYS_ADMIN
  #   # security_opt:
  #   #   - apparmor:unconfined